const socket=io(),$=id=>document.getElementById(id);let mode='home',code='',hostToken='',playerToken='',playerId='',state=null,catalog=[],activeRole='ALL',selectedPlayer=null,timerLoop=null;const params=new URLSearchParams(location.search);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');mode=id}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function roleName(r){return({P:'Portiere',D:'Difensore',C:'Centrocampista',A:'Attaccante'})[r]||r||''}
function statusName(s){return({waiting:'ATTESA',ready:'PRONTA',open:'APERTA',paused:'PAUSA',sold:'CHIUSA'})[s]||s}
function startTimer(){clearInterval(timerLoop);timerLoop=setInterval(()=>{if(!state)return;const left=state.endAt?Math.max(0,(state.endAt-Date.now())/1000):null;['hostTimer','playerTimer','tvTimer'].forEach(id=>{if($(id))$(id).textContent=left==null?'—':left.toFixed(1)})},100)}
function selectPlayer(p){selectedPlayer=p;$('itemInput').value=p.name;$('selectedName').textContent=p.name;$('selectedMeta').textContent=`${p.team} • ${roleName(p.role)}${p.quotation?` • Q ${p.quotation}`:''}`;renderCatalog()}
function renderCatalog(){if(!$('playersCatalog'))return;const q=($('playerSearch').value||'').toLowerCase();const assigned=new Set((state?.assignments||[]).map(a=>`${a.player}|${a.team}|${a.role}`.toLowerCase()));const f=catalog.filter(p=>(activeRole==='ALL'||p.role===activeRole)&&(!q||p.name.toLowerCase().includes(q)||p.team.toLowerCase().includes(q)));$('playersCatalog').innerHTML=f.map(p=>{const sold=assigned.has(`${p.name}|${p.team}|${p.role}`.toLowerCase());return `<button class="catalog-card ${selectedPlayer?.id===p.id?'selected':''} ${sold?'sold':''}" data-id="${esc(p.id)}" ${sold?'disabled':''}><span class="role-icon">${p.role}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.team)} • ${roleName(p.role)}${p.quotation?` • Q ${p.quotation}`:''}</small></span></button>`}).join('')||'<div class="empty-catalog">Nessun calciatore trovato.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectPlayer(catalog.find(p=>String(p.id)===b.dataset.id)));$('listStatus').textContent=`${catalog.length} calciatori caricati`}
async function loadCatalog(){try{const saved=localStorage.getItem('fbCatalogV1');if(saved)catalog=JSON.parse(saved);else{const d=await fetch('/players.json').then(r=>r.json());catalog=d.players||[]}}catch{}renderCatalog()}
function renderHistory(el,h){if(!el)return;el.innerHTML=(h||[]).slice().reverse().map(x=>`<p><span>${new Date(x.at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span>${esc(x.text)}</p>`).join('')||'<small>Nessun rilancio.</small>'}
function renderStats(s){$('statsTotal').textContent=`${s.stats.total} assegnazioni`;$('avgAll').textContent=s.stats.average;$('avgP').textContent=s.stats.byRole.P;$('avgD').textContent=s.stats.byRole.D;$('avgC').textContent=s.stats.byRole.C;$('avgA').textContent=s.stats.byRole.A;$('topBuys').innerHTML=s.stats.top.map((a,i)=>`<div class="rank-row"><b>${i+1}. ${esc(a.player)}</b><span>${esc(a.ownerName)} • ${a.price}</span></div>`).join('')||'<small>Nessun acquisto</small>';$('spendRank').innerHTML=s.stats.spend.map((p,i)=>`<div class="rank-row"><b>${i+1}. ${esc(p.name)}</b><span>${p.spent} spesi • ${p.remaining} residui</span></div>`).join('')||'<small>Nessun partecipante</small>'}
function renderRosters(s){$('assignmentCount').textContent=`${s.assignments.length} calciatori assegnati`;$('rostersView').innerHTML=s.players.map(p=>`<div class="roster-box"><h3>${esc(p.name)}</h3><div class="roster-summary">${p.roster.length} giocatori • ${p.spent} spesi • ${p.remaining} residui</div>${p.roster.map(x=>`<div class="roster-line"><b>${x.role}</b><span>${esc(x.player)}<small>${esc(x.team)}</small></span><strong>${x.price}</strong></div>`).join('')||'<small>Nessun acquisto</small>'}</div>`).join('')}
function renderPlayerCard(s){const me=s.players.find(p=>p.id===playerId);if(!me)return;$('myCredits').textContent=me.remaining;$('myMaxBid').textContent=me.maxBid;$('mySlots').textContent=`P ${me.counts.P}/${s.settings.limits.P} • D ${me.counts.D}/${s.settings.limits.D} • C ${me.counts.C}/${s.settings.limits.C} • A ${me.counts.A}/${s.settings.limits.A}`;$('myRoster').innerHTML=`<h3>La tua rosa</h3>${me.roster.map(x=>`<p><b>${x.role}</b> ${esc(x.player)} — ${esc(x.team)} <strong>${x.price}</strong></p>`).join('')||'<p>Nessun acquisto.</p>'}`}
function renderTV(s){$('tvCode').textContent=`STANZA ${s.code}`;$('tvPlayers').textContent=s.playerCount;$('tvItem').textContent=s.item||'In attesa';$('tvMeta').textContent=[s.itemTeam,roleName(s.itemRole)].filter(Boolean).join(' • ');$('tvBid').textContent=s.currentBid>=s.basePrice?s.currentBid:'—';$('tvLeader').textContent=s.leaderName?`In testa: ${s.leaderName}`:'Nessun offerente';$('tvTop').innerHTML=s.stats.top.slice(0,5).map(a=>`<div class="tv-row"><span>${esc(a.player)}</span><b>${a.price}</b></div>`).join('')||'<small>Nessun acquisto</small>';$('tvCredits').innerHTML=s.stats.spend.slice().sort((a,b)=>a.remaining-b.remaining).map(p=>`<div class="tv-row"><span>${esc(p.name)}</span><b>${p.remaining}</b></div>`).join('');$('tvLast').innerHTML=s.assignments.slice(-5).reverse().map(a=>`<div class="tv-row"><span>${esc(a.player)} → ${esc(a.ownerName)}</span><b>${a.price}</b></div>`).join('')||'<small>Nessuna aggiudicazione</small>'}
function render(s){state=s;if(mode==='host'){$('hostItem').textContent=s.item||'In attesa';$('hostItemMeta').textContent=[s.itemTeam,roleName(s.itemRole)].filter(Boolean).join(' • ');$('hostBid').textContent=s.currentBid>=s.basePrice?s.currentBid:'—';$('hostLeader').textContent=s.leaderName?`In testa: ${s.leaderName}`:'Nessun offerente';$('statusBadge').textContent=statusName(s.status);$('playerCount').textContent=s.playerCount;$('saveStatus').textContent=s.savedAt?`salvata ${new Date(s.savedAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`:'salvataggio automatico';$('playersList').innerHTML=s.players.map(p=>`<div class="credit-card"><div><strong>${p.connected?'●':'○'} ${esc(p.name)}</strong><small>${p.roster.length} giocatori • max ${p.maxBid}</small></div><div><b>${p.remaining}</b><small>residui</small></div><button data-kick="${p.id}">×</button></div>`).join('')||'<p>Nessun partecipante</p>';document.querySelectorAll('[data-kick]').forEach(b=>b.onclick=()=>hostAction('kick',{playerId:b.dataset.kick}));renderHistory($('hostHistory'),s.history);renderStats(s);renderRosters(s);renderCatalog()}else if(mode==='player'){$('playerItem').textContent=s.item||'In attesa del banditore';$('playerItemMeta').textContent=[s.itemTeam,roleName(s.itemRole)].filter(Boolean).join(' • ');$('playerBid').textContent=s.currentBid>=s.basePrice?s.currentBid:'—';$('playerLeader').textContent=s.leaderName?(s.leaderId===playerId?'🔥 Sei in testa!':`In testa: ${s.leaderName}`):'Nessun offerente';const open=s.status==='open';$('buzzBtn').disabled=!open;document.querySelectorAll('.increments button').forEach(b=>b.disabled=!open);$('playerMessage').textContent=open?'Premi per rilanciare. Il countdown riparte a ogni offerta.':s.status==='sold'?(s.leaderId===playerId?'🏆 Aggiudicato a te!':'Asta conclusa.'):'Aspetta l’apertura.';renderPlayerCard(s)}else if(mode==='tv')renderTV(s)}
function roomLinks(){const join=`${location.origin}/?room=${code}`,tv=`${location.origin}/?tv=${code}`;$('joinUrl').textContent=join;$('qrImage').src=`/qr?data=${encodeURIComponent(join)}&t=${Date.now()}`;$('tvQrImage').src=`/qr?data=${encodeURIComponent(tv)}&t=${Date.now()}`}
$('createBtn').onclick=()=>socket.emit('createRoom',{credits:$('creditsInput').value,minReserve:$('reserveInput').value,p:$('limitP').value,d:$('limitD').value,c:$('limitC').value,a:$('limitA').value},res=>{if(!res.ok)return $('homeError').textContent=res.error;code=res.code;hostToken=res.hostToken;localStorage.setItem('fbHostV1',JSON.stringify({code,hostToken}));history.replaceState(null,'',`/?host=${code}`);show('host');$('hostCode').textContent=code;roomLinks();render(res.state);startTimer()});
function join(){const c=($('joinCode').value||params.get('room')||'').toUpperCase().trim(),name=$('joinName').value.trim(),saved=JSON.parse(localStorage.getItem(`fbPlayer_${c}`)||'null');socket.emit('joinRoom',{code:c,name,playerToken:saved?.playerToken},res=>{if(!res.ok)return $('homeError').textContent=res.error;code=c;playerToken=res.playerToken;playerId=res.playerId;localStorage.setItem(`fbPlayer_${c}`,JSON.stringify({playerToken,playerId,name}));history.replaceState(null,'',`/?room=${code}`);show('player');$('playerIdentity').textContent=name;$('playerRoom').textContent=`STANZA ${code}`;render(res.state);startTimer()})}
$('joinBtn').onclick=join;$('joinName').addEventListener('keydown',e=>{if(e.key==='Enter')join()});
function hostAction(action,payload={}){socket.emit('hostAction',{code,hostToken,action,payload},res=>{if(!res.ok)toast(res.error)})}
$('prepareBtn').onclick=()=>hostAction('prepare',{item:$('itemInput').value,itemTeam:selectedPlayer?.team||'',itemRole:selectedPlayer?.role||'',basePrice:$('baseInput').value,duration:$('durationInput').value});$('startBtn').onclick=()=>hostAction('start');$('pauseBtn').onclick=()=>hostAction(state?.status==='paused'?'resume':'pause');$('sellBtn').onclick=()=>hostAction('sell');$('resetBtn').onclick=()=>hostAction('reset');$('exportBtn').onclick=$('exportBtn2').onclick=()=>location.href=`/export.xls?code=${encodeURIComponent(code)}&token=${encodeURIComponent(hostToken)}`;$('tvBtn').onclick=()=>window.open(`/?tv=${code}`,'_blank');
function bid(n){socket.emit('bid',{code,playerToken,increment:Number(n)},res=>{if(!res.ok)toast(res.error);else navigator.vibrate?.(35)})}$('buzzBtn').onclick=()=>bid(1);document.querySelectorAll('.increments button').forEach(b=>b.onclick=()=>bid(b.dataset.inc));
$('playerSearch').addEventListener('input',renderCatalog);document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{activeRole=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$('xlsInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);try{const d=await fetch('/import-listone',{method:'POST',body:fd}).then(r=>r.json());if(!d.ok)throw new Error(d.error);catalog=d.players;localStorage.setItem('fbCatalogV1',JSON.stringify(catalog));selectedPlayer=null;renderCatalog();toast(`${d.count} calciatori importati da ${d.file}`)}catch(err){toast(err.message)}});$('itemInput').addEventListener('input',()=>{if(selectedPlayer&&$('itemInput').value!==selectedPlayer.name){selectedPlayer=null;$('selectedName').textContent='Inserimento manuale';$('selectedMeta').textContent='Squadra e ruolo non associati';renderCatalog()}});
socket.on('state',render);socket.on('kicked',()=>{alert('Sei stato rimosso.');location.href='/'});socket.on('disconnect',()=>{if(mode==='player'){$('connectionDot').textContent='● OFFLINE';$('connectionDot').className='offline'}});socket.on('connect',()=>{if(mode==='player'){$('connectionDot').textContent='● ONLINE';$('connectionDot').className='online'}if(mode==='host'&&code&&hostToken)socket.emit('restoreHost',{code,hostToken},r=>r.ok&&render(r.state));if(mode==='tv'&&code)socket.emit('joinViewer',{code},r=>r.ok&&render(r.state));if(mode==='player'&&code&&playerToken){const s=JSON.parse(localStorage.getItem(`fbPlayer_${code}`)||'null');socket.emit('joinRoom',{code,name:s?.name||'Giocatore',playerToken},r=>r.ok&&render(r.state))}});
(function boot(){loadCatalog();const room=params.get('room');if(room){$('joinCode').value=room.toUpperCase();$('joinCode').readOnly=true}const tv=params.get('tv');if(tv){code=tv.toUpperCase();show('tv');socket.emit('joinViewer',{code},r=>{if(r.ok){render(r.state);startTimer()}else location.href='/'})}const host=params.get('host'),saved=JSON.parse(localStorage.getItem('fbHostV1')||'null');if(host&&saved?.code===host&&saved.hostToken){code=host;hostToken=saved.hostToken;socket.emit('restoreHost',{code,hostToken},r=>{if(!r.ok)return;show('host');$('hostCode').textContent=code;roomLinks();render(r.state);startTimer()})}})();
